version: '3.8'

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: ${STAGE}
    ports:
      - "${APP_PORT:8080}:8080"
    networks:
      - frontend
      - backend

volumes:
  pg-data:

networks:
  frontend:
  backend: