version: '3.8'

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "${DB_PORT:5432}:5432"

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: ${STAGE}
    ports:
      - "${APP_PORT:8080}:8080"
      - "${ADMIN_PORT:4848}:4848"
    networks:
      - frontend
      - backend

volumes:
  jeeminimal-pg-data:

networks:
  frontend:
  backend: