version: '3.8'

services:
  db:
    image: 'postgres:15.2-alpine'
    environment:
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - jeeminimal-pg-data:/var/lib/postgresql/data
    networks:
      - backend
  app:
    image: 'brunoe/jakartaee-minimal-jpa-jaxrs:micro-0.1.0'
    build:
      dockerfile: Dockerfile.payaramicro
    depends_on:
      - db
    environment:
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_NAME=${DB_NAME}"
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend

volumes:
  jeeminimal-pg-data:

networks:
  frontend:
  backend:
