version: '3.8'

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - backend

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: prod
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend: