name: Java CI with Docker and Maven

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches: [ "develop" ]

env:
  SONAR_URL: ${{ secrets.SONAR_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: [self-hosted, Linux]

    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Extract Maven project version
      run: echo VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) >> "$GITHUB_ENV"

    # The project is built and unit tested with docker
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and load docker image
      uses: docker/build-push-action@v5
      with:
        file: docker/Dockerfile
        load: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jakartaee-minimal-jpa-jaxrs:test

    # After integration tests, the project is analyzed with Sonar
    - name: Check quality
      run: ./mvnw -B verify --file pom.xml
    - name: run sonar with Maven in docker
      run: |
        ./mvnw verify
        ./mvnw sonar:sonar \
            -Dsonar.branch.name=${GITHUB_REF##*/} \
            -DskipTests=true \

    - name: Push docker image
      uses: docker/build-push-action@v5
      with:
        file: docker/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jakartaee-minimal-jpa-jaxrs:${{ env.VERSION }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
